### ISSUE TITLE
icon

### ISSUE THREAD

**Issue by very-real-person** [Thydekar/Tab-Cloaking-Bookmarklets-Reupload#1]
It always shows up as the globe and it is confusing
here is my code
javascript:(function() {var l = document.querySelector("link[rel*='icon']") || document.createElement('link');l.type = 'image/x-icon';l.rel = 'shortcut icon';l.href = 'https://user-images.githubusercontent.com/130446887/236890346-a33ab9eb-5493-4da8-af8d-b97a3414b458.png';document.getElementsByTagName('head')[0].appendChild(l);document.title = 'Home';})();

**Comment by Thydekar** [comment]
the issue with this code is that you added javascript into the image url. it would be 'https://user-images.githubusercontent.com/130446887/236890346-a33ab9eb-5493-4da8-af8d-b97a3414b458.png', not https://user-images.githubusercontent.com/130446887/236890346-a33ab9eb-5493-4da8-af8d-b97a3414b458.png';document.getElementsByTagName('head')%5B0%5D.appendChild(l);document.title

**Comment by Thydekar** [comment]
let me know if you have any further issues :)

**Comment by very-real-person** [comment]
Thank you!
